pub mod state;

pub const MODE_UNDO_NOT_SUPPORTED_IN_FOUNDATION: &str = "MODE_UNDO_NOT_SUPPORTED_IN_FOUNDATION";
pub const UNIFIED_ASSISTANT_NOT_IMPLEMENTED: &str = "UNIFIED_ASSISTANT_NOT_IMPLEMENTED";
